[package]
name = "asmedia-xhc-trace"
authors = ["cyrozap"]
license = "GPL-3.0-or-later"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
memmap = "0.7.0"
