= ASM1142 USB Host Controller Programming Manual
:doctype: book
:reproducible:
:sectnums:
:sectlinks:
:stem:
:icons: font
:toc: left
:toclevels: 4


== System Overview

The ASM1142 is a USB host controller with an MCS-51-compatible CPU running at up to 156.25 MHz, 64 kB boot ROM, 64 kB of code RAM, 256 B internal data RAM, 48 kB of external data RAM, PCIe and USB controller peripherals, and supporting peripherals.

Interesting features include:

* One machine cycle per clock cycle (1T).
* Code RAM writable from the device CPU.
* Hardware-accelerated memcpy and memset.
* Mailbox registers in PCI configuration space.
* DMA over PCIe.


== Memory Architecture and Access

The ASM1142's MCS-51-compatible CPU can address several memory regions: program/code memory (CODE), external data (XDATA), direct/indirect internal data (IRAM), and special function registers (SFRs).
XRAM is located at address zero in XDATA, and MMIO begins at XDATA address 0xE000.


=== CPU Access

Architecturally, CODE is read-only, and can be accessed using MOVC instructions.
XDATA is read/write, and can be accessed using MOVX instructions.
The lower 128 bytes of IRAM can be accessed either directly or indirectly, but the upper 128 bytes can only be accessed indirectly.
SFRs are accessed using direct reads/writes to the upper 128 bytes of IRAM.

While CODE is architecturally read-only, in the ASM1142 the CODE memory space can be mapped to either boot ROM or code RAM, and code RAM can be written to in several ways.
One method, which is used by the boot ROM, is to direct the SPI flash controller to write the data it reads directly into code RAM.
Unfortunately, it is not possible to do this while executing out of code RAM, so this capability is not particularly useful for custom firmware.

The other method of writing to code RAM, which is usable by code running from code RAM, is to set bit 4 of the PCON SFR, then use a MOVX instruction to read or write data in code RAM the same way MOVX is normally used to access XDATA.
After accessing code RAM, bit 4 of PCON should be cleared so that XDATA access will work again.


=== Host Access

The host can access certain memory regions through the PCI configuration space.
This access can be organized into three major categories: firmware-assisted access, direct MMIO access, and direct code RAM write.


==== Firmware-assisted Access

Firmware-assisted access, as its name implies, is memory accessed by communicating with the currently-running firmware.
As this is firmware-specific, and not a function of the hardware, it will not be discussed further, other than to say that any memory that can be accessed by the firmware can be accessed by the host by communicating with the running firmware.


==== Direct MMIO Access

Direct MMIO access can be performed as follows:

. Write the address of the MMIO register to the `MMIO_ACCESS.ADDRESS` register in PCI configuration space.
. Repeatedly read the `MMIO_ACCESS.ADDRESS` register until the address in the register matches the address of the MMIO register you want to access.
. If you want to write data to the MMIO register, do so by writing the data to `MMIO_ACCESS.WRITE_DATA`.
If you want to read data, you can do so by reading from `MMIO_ACCESS.READ_DATA`.

Note that while writes to `MMIO_ACCESS.WRITE_DATA` take effect immediately, and can be performed repeatedly without writing the MMIO address another time, if you want to read updated data from the selected MMIO register, a second write to `MMIO_ACCESS.ADDRESS` is required to latch the new data into `MMIO_ACCESS.READ_DATA`.


==== Code RAM Write Access

Code RAM can be written to (but not read from) directly by the host, which enables the host to load firmware directly into the device without first writing it to flash.
Data is written in 2-byte chunks and must be aligned on 2-byte boundaries, and the address auto-increments by two on every write.
The address register can only be used to address 32 kB of memory (the high bit, bit 15, is permanently zero), so the highest bit of the address is set or cleared depending on which data register is written to (enabling access to the full 64 kB).

The process to write data to code RAM is as follows:

. Enable writing to code RAM by using <<Direct MMIO Access>> to set bit 1 in `CPU_MISC`.
. Write the code RAM destination address to `CODE_RAM_ADDR` in PCI configuration space.
. For addresses less than 0x8000, write two bytes of the code RAM data in a single writew operation to `CODE_RAM_DATA.LOWER_BANK_DATA` in PCI configuration space.
For addresses greater than or equal to 0x8000, write the code RAM data to `CODE_RAM_DATA.UPPER_BANK_DATA` instead.
. For each 2-byte chunk of code RAM data remaining, repeat step 3 (the address auto-increments so repeating step 2 is not necessary).


== Clocking

TODO


== Boot Process

After reset, the CPU begins executing from the boot ROM.
The boot ROM's primary responsibility is to do some minor hardware initialization before loading and executing code from SPI flash.
If the SPI flash is not present, or if the firmware image in flash is not valid, the boot ROM will continue to initialize hardware and wait in a loop until it is commanded to do something by the host.


=== Flash Firmware Loading

Normally, code is loaded from flash by the boot ROM.

TODO: Explain how this process works in more detail.


=== Direct Firmware Loading

It is possible to load firmware directly into the code RAM of the ASM1142, without the host communicating with the boot ROM.
This means that writing to the attached SPI flash is not necessary in order to run custom code on the ASM1142.
It also means that firmware can be repeatedly loaded, as during development.

To boot by directly loading firmware, perform the following steps:

. Halt the device CPU and hold it in reset by using <<Direct MMIO Access>> to write 0x02 to `CPU_EXEC_CTRL`.
. Write the firmware to code RAM using <<Code RAM Write Access>>.
. Configure the device CPU to boot from code RAM by using <<Direct MMIO Access>> to set bit 0 in `CPU_MODE_NEXT`.
. Release the device CPU from reset by using <<Direct MMIO Access>> to write 0x00 to `CPU_EXEC_CTRL`.


== Peripherals

TODO


=== Hardware Copy Controller

The Hardware Copy Controller has two main modes of operation:

. XRAM-to-XRAM copy ("memcpy" mode).
. SFR region scratch registers-to-XRAM copy ("memset" mode).

In the first mode, the controller is used to copy data between locations in XRAM.
In other words, it's essentially an accelerated memcpy.

In the second mode, data in SFRs 0xC0-0xCF can be copied in a loop into XRAM.
This can be used to repeatedly write an arbitrary 16-byte pattern of data to a much larger region of XRAM (which can be used to accelerate memset operations).


==== Initialization

TODO


==== Usage

TODO


=== Mailbox

TODO


==== Initialization

TODO


==== Usage

TODO


=== UART

TODO


==== Initialization

The UART comes out of reset with parity enabled (mode 8O1), so if you want the mode to be 8N1 you need to explicitly configure that.

TODO: Explain full initialization process.


==== Usage

TODO


=== Timer

The timer peripheral is used for setting precise delays and timeouts, and can optionally be used to trigger <<External Interrupt 1 (EINT1)>>.
It is comprised of a counter, a clock divider/prescaler, a threshold value register, and an interrupt output.
The counter is the core of the timer, and increments by one on every tick of the timer clock.
The clock divider/prescaler can be used to control the speed of the timer clock.
The threshold value register contains the threshold value, which is the value at which the counter will stop and the `TIMER_CSR.THRESHOLD_MET` bit will be set.
The interrupt output is used to trigger <<External Interrupt 1 (EINT1)>> when the the `TIMER_CSR.THRESHOLD_MET` bit is set.

The timer is only capable of being used in a one-shot mode.
Once it's started, on every tick of the timer clock the value in the counter is increased by one.
When the value in the counter meets (TODO: determine if it's "meets" or "exceeds") the value in the threshold register `TIMER_THRESHOLD`, the counter will stop, the `TIMER_CSR.THRESHOLD_MET` bit will be set, and the `TIMER_CSR.RUN` bit will be cleared.
If the `TIMER_IE.EX1` bit is set, <<External Interrupt 1 (EINT1)>> will be triggered when the `TIMER_CSR.THRESHOLD_MET` bit is set.

The timer can be stopped at any time before the threshold is met.
To do so, simply clear the `TIMER_CSR.RUN` bit.
Doing so will/will not (TODO: determine if the timer be "paused" and "resumed") reset the counter back to zero.

WARNING: The timer has an error in its implementation that can cause the counter to stop and the `TIMER_CSR.THRESHOLD_MET` bit to be set immediately as soon as the timer is started.
To avoid triggering the bug, please follow the timer programming instructions in the <<timer-usage,Usage>> section exactly.
For more details on this issue, please see the timer's <<timer-errata,Errata>>.


[#timer-usage]
==== Usage

CAUTION: Please follow these directions exactly.
Failing to do so may cause the timer to function improperly.

To start the timer:

. Calculate the values for `TIMER_DIV` and `TIMER_THRESHOLD` as specified in <<timer-config,Configuration>>.
. Reset the timer by first writing 0x00 to `TIMER_CSR`, and then writing 0x02.
. Set `TIMER_DIV` to one.
. Set `TIMER_THRESHOLD` to zero.
. Trigger the hardware bug (see <<timer-errata,Errata>>) by writing 0x01 to `TIMER_CSR`.
. Wait for the timer to stop by waiting for the `TIMER_CSR.RUN` bit to be cleared by hardware.
. Reset the timer by writing 0x02 to `TIMER_CSR`.
. Set the desired `TIMER_DIV` and `TIMER_THRESHOLD` values.
. Optionally, set `TIMER_IE.EX1` to enable triggering an interrupt.
. Start the timer by writing 0x01 to `TIMER_CSR`.

To check the status of the timer:

. Read the `TIMER_CSR` register and check the state of the `TIMER_CSR.THRESHOLD_MET` bit.

To stop the timer early:

. Write 0x00 to the `TIMER_CSR` register.


[#timer-config]
==== Configuration

The timer's clock frequency is derived from the current CPU clock frequency, and can be calculated with the following formula:

[latexmath]
++++
f_{timer} = \frac {f_{cpu}} {8192 \times TIMER\_DIV}
++++

Where latexmath:[f_{timer}] is the timer clock frequency in Hz, latexmath:[f_{cpu}] is the current CPU clock frequency in Hz (see <<Clocking>>), and latexmath:[TIMER\_DIV] is the current value of the `TIMER_DIV` register.

The time it will take for the `TIMER_CSR.THRESHOLD_MET` to be set after the timer is started can be calculated with the following formula:

[latexmath]
++++
t = \frac {TIMER\_THRESHOLD} {f_{timer}}
++++

Where latexmath:[t] is the time it will take, in seconds, for the counter to reach the threshold value, latexmath:[TIMER\_THRESHOLD] is the current value of the `TIMER_THRESHOLD` register, and latexmath:[f_{timer}] is the timer clock frequency in Hz.

Substituting in the formula for latexmath:[f_{timer}], we get:

[latexmath]
++++
t = \frac {8192 \times TIMER\_DIV \times TIMER\_THRESHOLD} {f_{cpu}}
++++

Rearranging to make latexmath:[t] an independent variable, we get:

[latexmath]
++++
TIMER\_DIV \times TIMER\_THRESHOLD = \frac {t \times f_{cpu}} {8192}
++++

Since `TIMER_DIV` is only 8 bits and `TIMER_THRESHOLD` is 16 bits, the best way to determine the optimal values of those registers for an arbitrary latexmath:[t] is to do the following:

. Assume `TIMER_DIV` is 1.
. Solve for `TIMER_THRESHOLD`.
. If the solved-for `TIMER_THRESHOLD` is greater than 65535, increase `TIMER_DIV` until the value of `TIMER_THRESHOLD` is less than or equal to 65535.
. If the value of `TIMER_DIV` is greater than 255, then the timer can not be programmed for that timeout value.


[#timer-errata]
==== Errata

The timer has an error in its implementation that can cause the counter to stop and the `TIMER_CSR.THRESHOLD_MET` bit to be set immediately as soon as the timer is started.
This bug will be triggered if any of the following conditions are met:

* The previous run of the timer was not stopped before the counter met the threshold value.
* The timer was run with the threshold value set to zero.

After the bug is triggered, the timer will behave normally on the immediately following run.

The erroneous behavior can be detected by reading the `TIMER_CSR` immediately after setting the `TIMER_CSR.RUN` bit.
If the value of the register is 0x03, then the bug was definitely triggered.
If the value of the register is 0x02, then the bug was most likely triggered, but the read from `TIMER_CSR` took more than a few instructions.

To work around this issue, the bug must be deliberately triggered before each use of the timer.
To do so, simply set the threshold value `TIMER_THRESHOLD` to zero and then run the timer.
This will trigger the bug, meaning the next time the timer runs it will work properly.


=== SPI Flash Controller

Packet format:

* 1 command byte
* 0-3 address bytes (transmitted)
* 0-65535 data bytes (transmitted or received, depending on the value of FLASH_CON_MODE.WRITE_N_READ)

Can read data into either XRAM or code RAM.

Supports CRC calculation on data read from flash, standard CRC algo (Ethernet/zlib).

TODO: Elaborate on capabilities.


==== Initialization

TODO


==== Usage

TODO: Explain SPI transactions and CRC calculation.


== Interrupts

The ASM1142 appears to only support two primary interrupt sources, the external interrupts EINT0 and EINT1.
However, both primary interrupts can be triggered by multiple sources, and the interrupt service routines are responsible for determining which source triggered an interrupt.

TODO: Explain interrupt masking.


=== External Interrupt 0 (EINT0)

EINT0 has several sources:

* UART
* Others TBD

TODO: Include interrupt routing diagram.


=== External Interrupt 1 (EINT1)

EINT1 has several sources:

* Timer
* Mailbox read ACK/write start
* Others TBD

TODO: Include interrupt routing diagram.
